@startuml

class Client{

}

interface Duck{
  quack();
  fly();
}

interface Turkey{
  gobble();
  fly();
}

class DuckAdapter{
      quack();
      fly();
}

Client --> Duck
DuckAdapter --> Turkey
Duck <|.. DuckAdapter



@enduml